# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'game_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgame_ai.proto\x12\x07game_ai\"k\n\x0bPlayerState\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nhp_percent\x18\x05 \x01(\x05\x12\x13\n\x0b\x64rive_gauge\x18\x06 \x01(\x05\"J\n\x0c\x46rameRequest\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\"\x8f\x01\n\rFrameResponse\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12&\n\x08p1_state\x18\x02 \x01(\x0b\x32\x14.game_ai.PlayerState\x12&\n\x08p2_state\x18\x03 \x01(\x0b\x32\x14.game_ai.PlayerState\x12\x1c\n\x14inference_latency_ms\x18\x04 \x01(\x05\x32I\n\x08VisionAI\x12=\n\x0c\x41nalyzeFrame\x12\x15.game_ai.FrameRequest\x1a\x16.game_ai.FrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERSTATE']._serialized_start=26
  _globals['_PLAYERSTATE']._serialized_end=133
  _globals['_FRAMEREQUEST']._serialized_start=135
  _globals['_FRAMEREQUEST']._serialized_end=209
  _globals['_FRAMERESPONSE']._serialized_start=212
  _globals['_FRAMERESPONSE']._serialized_end=355
  _globals['_VISIONAI']._serialized_start=357
  _globals['_VISIONAI']._serialized_end=430
# @@protoc_insertion_point(module_scope)
