// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game_ai.proto

#include "game_ai.pb.h"
#include "game_ai.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace game_ai {

static const char* VisionAI_method_names[] = {
  "/game_ai.VisionAI/AnalyzeFrame",
};

std::unique_ptr< VisionAI::Stub> VisionAI::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VisionAI::Stub> stub(new VisionAI::Stub(channel, options));
  return stub;
}

VisionAI::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AnalyzeFrame_(VisionAI_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VisionAI::Stub::AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::game_ai::FrameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::game_ai::FrameRequest, ::game_ai::FrameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AnalyzeFrame_, context, request, response);
}

void VisionAI::Stub::async::AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::game_ai::FrameRequest, ::game_ai::FrameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeFrame_, context, request, response, std::move(f));
}

void VisionAI::Stub::async::AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AnalyzeFrame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>* VisionAI::Stub::PrepareAsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::game_ai::FrameResponse, ::game_ai::FrameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AnalyzeFrame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>* VisionAI::Stub::AsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAnalyzeFrameRaw(context, request, cq);
  result->StartCall();
  return result;
}

VisionAI::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionAI_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionAI::Service, ::game_ai::FrameRequest, ::game_ai::FrameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VisionAI::Service* service,
             ::grpc::ServerContext* ctx,
             const ::game_ai::FrameRequest* req,
             ::game_ai::FrameResponse* resp) {
               return service->AnalyzeFrame(ctx, req, resp);
             }, this)));
}

VisionAI::Service::~Service() {
}

::grpc::Status VisionAI::Service::AnalyzeFrame(::grpc::ServerContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace game_ai

