// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game_ai.proto
#ifndef GRPC_game_5fai_2eproto__INCLUDED
#define GRPC_game_5fai_2eproto__INCLUDED

#include "game_ai.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace game_ai {

// ---------------------------------------------------------
// 3. 微服务接口定义 (Service)
// ---------------------------------------------------------
class VisionAI final {
 public:
  static constexpr char const* service_full_name() {
    return "game_ai.VisionAI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::game_ai::FrameResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>> AsyncAnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>>(AsyncAnalyzeFrameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>> PrepareAsyncAnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>>(PrepareAsyncAnalyzeFrameRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>* AsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::game_ai::FrameResponse>* PrepareAsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::game_ai::FrameResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>> AsyncAnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>>(AsyncAnalyzeFrameRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>> PrepareAsyncAnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>>(PrepareAsyncAnalyzeFrameRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, std::function<void(::grpc::Status)>) override;
      void AnalyzeFrame(::grpc::ClientContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>* AsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::game_ai::FrameResponse>* PrepareAsyncAnalyzeFrameRaw(::grpc::ClientContext* context, const ::game_ai::FrameRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AnalyzeFrame_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AnalyzeFrame(::grpc::ServerContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeFrame(::grpc::ServerContext* context, ::game_ai::FrameRequest* request, ::grpc::ServerAsyncResponseWriter< ::game_ai::FrameResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AnalyzeFrame<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::game_ai::FrameRequest, ::game_ai::FrameResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::game_ai::FrameRequest* request, ::game_ai::FrameResponse* response) { return this->AnalyzeFrame(context, request, response); }));}
    void SetMessageAllocatorFor_AnalyzeFrame(
        ::grpc::MessageAllocator< ::game_ai::FrameRequest, ::game_ai::FrameResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::game_ai::FrameRequest, ::game_ai::FrameResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeFrame(
      ::grpc::CallbackServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AnalyzeFrame<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAnalyzeFrame(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AnalyzeFrame(context, request, response); }));
    }
    ~WithRawCallbackMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AnalyzeFrame(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AnalyzeFrame : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AnalyzeFrame() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::game_ai::FrameRequest, ::game_ai::FrameResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::game_ai::FrameRequest, ::game_ai::FrameResponse>* streamer) {
                       return this->StreamedAnalyzeFrame(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AnalyzeFrame() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AnalyzeFrame(::grpc::ServerContext* /*context*/, const ::game_ai::FrameRequest* /*request*/, ::game_ai::FrameResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAnalyzeFrame(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::game_ai::FrameRequest,::game_ai::FrameResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AnalyzeFrame<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AnalyzeFrame<Service > StreamedService;
};

}  // namespace game_ai


#endif  // GRPC_game_5fai_2eproto__INCLUDED
