// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_ai.proto

#include "game_ai.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace game_ai {
PROTOBUF_CONSTEXPR PlayerState::PlayerState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.width_)*/0
  , /*decltype(_impl_.height_)*/0
  , /*decltype(_impl_.hp_percent_)*/0
  , /*decltype(_impl_.drive_gauge_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerStateDefaultTypeInternal() {}
  union {
    PlayerState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
PROTOBUF_CONSTEXPR FrameRequest::FrameRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.image_data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.frame_id_)*/uint64_t{0u}
  , /*decltype(_impl_.timestamp_ms_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FrameRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameRequestDefaultTypeInternal() {}
  union {
    FrameRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameRequestDefaultTypeInternal _FrameRequest_default_instance_;
PROTOBUF_CONSTEXPR FrameResponse::FrameResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.p1_state_)*/nullptr
  , /*decltype(_impl_.p2_state_)*/nullptr
  , /*decltype(_impl_.frame_id_)*/uint64_t{0u}
  , /*decltype(_impl_.inference_latency_ms_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FrameResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameResponseDefaultTypeInternal() {}
  union {
    FrameResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameResponseDefaultTypeInternal _FrameResponse_default_instance_;
}  // namespace game_ai
static ::_pb::Metadata file_level_metadata_game_5fai_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_game_5fai_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_game_5fai_2eproto = nullptr;

const uint32_t TableStruct_game_5fai_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.width_),
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.height_),
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.hp_percent_),
  PROTOBUF_FIELD_OFFSET(::game_ai::PlayerState, _impl_.drive_gauge_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameRequest, _impl_.frame_id_),
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameRequest, _impl_.timestamp_ms_),
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameRequest, _impl_.image_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameResponse, _impl_.frame_id_),
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameResponse, _impl_.p1_state_),
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameResponse, _impl_.p2_state_),
  PROTOBUF_FIELD_OFFSET(::game_ai::FrameResponse, _impl_.inference_latency_ms_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::game_ai::PlayerState)},
  { 12, -1, -1, sizeof(::game_ai::FrameRequest)},
  { 21, -1, -1, sizeof(::game_ai::FrameResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::game_ai::_PlayerState_default_instance_._instance,
  &::game_ai::_FrameRequest_default_instance_._instance,
  &::game_ai::_FrameResponse_default_instance_._instance,
};

const char descriptor_table_protodef_game_5fai_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rgame_ai.proto\022\007game_ai\"k\n\013PlayerState\022"
  "\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\r\n\005width\030\003 \001(\002\022\016\n\006"
  "height\030\004 \001(\002\022\022\n\nhp_percent\030\005 \001(\005\022\023\n\013driv"
  "e_gauge\030\006 \001(\005\"J\n\014FrameRequest\022\020\n\010frame_i"
  "d\030\001 \001(\004\022\024\n\014timestamp_ms\030\002 \001(\004\022\022\n\nimage_d"
  "ata\030\003 \001(\014\"\217\001\n\rFrameResponse\022\020\n\010frame_id\030"
  "\001 \001(\004\022&\n\010p1_state\030\002 \001(\0132\024.game_ai.Player"
  "State\022&\n\010p2_state\030\003 \001(\0132\024.game_ai.Player"
  "State\022\034\n\024inference_latency_ms\030\004 \001(\0052I\n\010V"
  "isionAI\022=\n\014AnalyzeFrame\022\025.game_ai.FrameR"
  "equest\032\026.game_ai.FrameResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_game_5fai_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_game_5fai_2eproto = {
    false, false, 438, descriptor_table_protodef_game_5fai_2eproto,
    "game_ai.proto",
    &descriptor_table_game_5fai_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_game_5fai_2eproto::offsets,
    file_level_metadata_game_5fai_2eproto, file_level_enum_descriptors_game_5fai_2eproto,
    file_level_service_descriptors_game_5fai_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_game_5fai_2eproto_getter() {
  return &descriptor_table_game_5fai_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_game_5fai_2eproto(&descriptor_table_game_5fai_2eproto);
namespace game_ai {

// ===================================================================

class PlayerState::_Internal {
 public:
};

PlayerState::PlayerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_ai.PlayerState)
}
PlayerState::PlayerState(const PlayerState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.width_){}
    , decltype(_impl_.height_){}
    , decltype(_impl_.hp_percent_){}
    , decltype(_impl_.drive_gauge_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.drive_gauge_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.drive_gauge_));
  // @@protoc_insertion_point(copy_constructor:game_ai.PlayerState)
}

inline void PlayerState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.width_){0}
    , decltype(_impl_.height_){0}
    , decltype(_impl_.hp_percent_){0}
    , decltype(_impl_.drive_gauge_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerState::~PlayerState() {
  // @@protoc_insertion_point(destructor:game_ai.PlayerState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerState::Clear() {
// @@protoc_insertion_point(message_clear_start:game_ai.PlayerState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.drive_gauge_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.drive_gauge_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float width = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float height = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.height_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 hp_percent = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hp_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 drive_gauge = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.drive_gauge_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_ai.PlayerState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float width = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = this->_internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_width(), target);
  }

  // float height = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = this->_internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_height(), target);
  }

  // int32 hp_percent = 5;
  if (this->_internal_hp_percent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_hp_percent(), target);
  }

  // int32 drive_gauge = 6;
  if (this->_internal_drive_gauge() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_drive_gauge(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_ai.PlayerState)
  return target;
}

size_t PlayerState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_ai.PlayerState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float width = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = this->_internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    total_size += 1 + 4;
  }

  // float height = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = this->_internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    total_size += 1 + 4;
  }

  // int32 hp_percent = 5;
  if (this->_internal_hp_percent() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hp_percent());
  }

  // int32 drive_gauge = 6;
  if (this->_internal_drive_gauge() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_drive_gauge());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerState::GetClassData() const { return &_class_data_; }


void PlayerState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerState*>(&to_msg);
  auto& from = static_cast<const PlayerState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_ai.PlayerState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_width = from._internal_width();
  uint32_t raw_width;
  memcpy(&raw_width, &tmp_width, sizeof(tmp_width));
  if (raw_width != 0) {
    _this->_internal_set_width(from._internal_width());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_height = from._internal_height();
  uint32_t raw_height;
  memcpy(&raw_height, &tmp_height, sizeof(tmp_height));
  if (raw_height != 0) {
    _this->_internal_set_height(from._internal_height());
  }
  if (from._internal_hp_percent() != 0) {
    _this->_internal_set_hp_percent(from._internal_hp_percent());
  }
  if (from._internal_drive_gauge() != 0) {
    _this->_internal_set_drive_gauge(from._internal_drive_gauge());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerState::CopyFrom(const PlayerState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_ai.PlayerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerState::IsInitialized() const {
  return true;
}

void PlayerState::InternalSwap(PlayerState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerState, _impl_.drive_gauge_)
      + sizeof(PlayerState::_impl_.drive_gauge_)
      - PROTOBUF_FIELD_OFFSET(PlayerState, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fai_2eproto_getter, &descriptor_table_game_5fai_2eproto_once,
      file_level_metadata_game_5fai_2eproto[0]);
}

// ===================================================================

class FrameRequest::_Internal {
 public:
};

FrameRequest::FrameRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_ai.FrameRequest)
}
FrameRequest::FrameRequest(const FrameRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FrameRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.image_data_){}
    , decltype(_impl_.frame_id_){}
    , decltype(_impl_.timestamp_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.image_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.image_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_image_data().empty()) {
    _this->_impl_.image_data_.Set(from._internal_image_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.frame_id_, &from._impl_.frame_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_ms_) -
    reinterpret_cast<char*>(&_impl_.frame_id_)) + sizeof(_impl_.timestamp_ms_));
  // @@protoc_insertion_point(copy_constructor:game_ai.FrameRequest)
}

inline void FrameRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.image_data_){}
    , decltype(_impl_.frame_id_){uint64_t{0u}}
    , decltype(_impl_.timestamp_ms_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.image_data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.image_data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FrameRequest::~FrameRequest() {
  // @@protoc_insertion_point(destructor:game_ai.FrameRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FrameRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.image_data_.Destroy();
}

void FrameRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FrameRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:game_ai.FrameRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_data_.ClearToEmpty();
  ::memset(&_impl_.frame_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_ms_) -
      reinterpret_cast<char*>(&_impl_.frame_id_)) + sizeof(_impl_.timestamp_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FrameRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 frame_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frame_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 timestamp_ms = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.timestamp_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes image_data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_image_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FrameRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_ai.FrameRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_frame_id(), target);
  }

  // uint64 timestamp_ms = 2;
  if (this->_internal_timestamp_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_timestamp_ms(), target);
  }

  // bytes image_data = 3;
  if (!this->_internal_image_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_image_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_ai.FrameRequest)
  return target;
}

size_t FrameRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_ai.FrameRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes image_data = 3;
  if (!this->_internal_image_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_image_data());
  }

  // uint64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frame_id());
  }

  // uint64 timestamp_ms = 2;
  if (this->_internal_timestamp_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FrameRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FrameRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FrameRequest::GetClassData() const { return &_class_data_; }


void FrameRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FrameRequest*>(&to_msg);
  auto& from = static_cast<const FrameRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_ai.FrameRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image_data().empty()) {
    _this->_internal_set_image_data(from._internal_image_data());
  }
  if (from._internal_frame_id() != 0) {
    _this->_internal_set_frame_id(from._internal_frame_id());
  }
  if (from._internal_timestamp_ms() != 0) {
    _this->_internal_set_timestamp_ms(from._internal_timestamp_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FrameRequest::CopyFrom(const FrameRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_ai.FrameRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameRequest::IsInitialized() const {
  return true;
}

void FrameRequest::InternalSwap(FrameRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.image_data_, lhs_arena,
      &other->_impl_.image_data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameRequest, _impl_.timestamp_ms_)
      + sizeof(FrameRequest::_impl_.timestamp_ms_)
      - PROTOBUF_FIELD_OFFSET(FrameRequest, _impl_.frame_id_)>(
          reinterpret_cast<char*>(&_impl_.frame_id_),
          reinterpret_cast<char*>(&other->_impl_.frame_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FrameRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fai_2eproto_getter, &descriptor_table_game_5fai_2eproto_once,
      file_level_metadata_game_5fai_2eproto[1]);
}

// ===================================================================

class FrameResponse::_Internal {
 public:
  static const ::game_ai::PlayerState& p1_state(const FrameResponse* msg);
  static const ::game_ai::PlayerState& p2_state(const FrameResponse* msg);
};

const ::game_ai::PlayerState&
FrameResponse::_Internal::p1_state(const FrameResponse* msg) {
  return *msg->_impl_.p1_state_;
}
const ::game_ai::PlayerState&
FrameResponse::_Internal::p2_state(const FrameResponse* msg) {
  return *msg->_impl_.p2_state_;
}
FrameResponse::FrameResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:game_ai.FrameResponse)
}
FrameResponse::FrameResponse(const FrameResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FrameResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.p1_state_){nullptr}
    , decltype(_impl_.p2_state_){nullptr}
    , decltype(_impl_.frame_id_){}
    , decltype(_impl_.inference_latency_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_p1_state()) {
    _this->_impl_.p1_state_ = new ::game_ai::PlayerState(*from._impl_.p1_state_);
  }
  if (from._internal_has_p2_state()) {
    _this->_impl_.p2_state_ = new ::game_ai::PlayerState(*from._impl_.p2_state_);
  }
  ::memcpy(&_impl_.frame_id_, &from._impl_.frame_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.inference_latency_ms_) -
    reinterpret_cast<char*>(&_impl_.frame_id_)) + sizeof(_impl_.inference_latency_ms_));
  // @@protoc_insertion_point(copy_constructor:game_ai.FrameResponse)
}

inline void FrameResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.p1_state_){nullptr}
    , decltype(_impl_.p2_state_){nullptr}
    , decltype(_impl_.frame_id_){uint64_t{0u}}
    , decltype(_impl_.inference_latency_ms_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FrameResponse::~FrameResponse() {
  // @@protoc_insertion_point(destructor:game_ai.FrameResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FrameResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.p1_state_;
  if (this != internal_default_instance()) delete _impl_.p2_state_;
}

void FrameResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FrameResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:game_ai.FrameResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.p1_state_ != nullptr) {
    delete _impl_.p1_state_;
  }
  _impl_.p1_state_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.p2_state_ != nullptr) {
    delete _impl_.p2_state_;
  }
  _impl_.p2_state_ = nullptr;
  ::memset(&_impl_.frame_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.inference_latency_ms_) -
      reinterpret_cast<char*>(&_impl_.frame_id_)) + sizeof(_impl_.inference_latency_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FrameResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 frame_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.frame_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .game_ai.PlayerState p1_state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_p1_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .game_ai.PlayerState p2_state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_p2_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 inference_latency_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.inference_latency_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FrameResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:game_ai.FrameResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_frame_id(), target);
  }

  // .game_ai.PlayerState p1_state = 2;
  if (this->_internal_has_p1_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::p1_state(this),
        _Internal::p1_state(this).GetCachedSize(), target, stream);
  }

  // .game_ai.PlayerState p2_state = 3;
  if (this->_internal_has_p2_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::p2_state(this),
        _Internal::p2_state(this).GetCachedSize(), target, stream);
  }

  // int32 inference_latency_ms = 4;
  if (this->_internal_inference_latency_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_inference_latency_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:game_ai.FrameResponse)
  return target;
}

size_t FrameResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:game_ai.FrameResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .game_ai.PlayerState p1_state = 2;
  if (this->_internal_has_p1_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.p1_state_);
  }

  // .game_ai.PlayerState p2_state = 3;
  if (this->_internal_has_p2_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.p2_state_);
  }

  // uint64 frame_id = 1;
  if (this->_internal_frame_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_frame_id());
  }

  // int32 inference_latency_ms = 4;
  if (this->_internal_inference_latency_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_inference_latency_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FrameResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FrameResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FrameResponse::GetClassData() const { return &_class_data_; }


void FrameResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FrameResponse*>(&to_msg);
  auto& from = static_cast<const FrameResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game_ai.FrameResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_p1_state()) {
    _this->_internal_mutable_p1_state()->::game_ai::PlayerState::MergeFrom(
        from._internal_p1_state());
  }
  if (from._internal_has_p2_state()) {
    _this->_internal_mutable_p2_state()->::game_ai::PlayerState::MergeFrom(
        from._internal_p2_state());
  }
  if (from._internal_frame_id() != 0) {
    _this->_internal_set_frame_id(from._internal_frame_id());
  }
  if (from._internal_inference_latency_ms() != 0) {
    _this->_internal_set_inference_latency_ms(from._internal_inference_latency_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FrameResponse::CopyFrom(const FrameResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game_ai.FrameResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FrameResponse::IsInitialized() const {
  return true;
}

void FrameResponse::InternalSwap(FrameResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameResponse, _impl_.inference_latency_ms_)
      + sizeof(FrameResponse::_impl_.inference_latency_ms_)
      - PROTOBUF_FIELD_OFFSET(FrameResponse, _impl_.p1_state_)>(
          reinterpret_cast<char*>(&_impl_.p1_state_),
          reinterpret_cast<char*>(&other->_impl_.p1_state_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FrameResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fai_2eproto_getter, &descriptor_table_game_5fai_2eproto_once,
      file_level_metadata_game_5fai_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace game_ai
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::game_ai::PlayerState*
Arena::CreateMaybeMessage< ::game_ai::PlayerState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_ai::PlayerState >(arena);
}
template<> PROTOBUF_NOINLINE ::game_ai::FrameRequest*
Arena::CreateMaybeMessage< ::game_ai::FrameRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_ai::FrameRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::game_ai::FrameResponse*
Arena::CreateMaybeMessage< ::game_ai::FrameResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::game_ai::FrameResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
