// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_ai.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_5fai_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_5fai_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_5fai_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5fai_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_5fai_2eproto;
namespace game_ai {
class FrameRequest;
struct FrameRequestDefaultTypeInternal;
extern FrameRequestDefaultTypeInternal _FrameRequest_default_instance_;
class FrameResponse;
struct FrameResponseDefaultTypeInternal;
extern FrameResponseDefaultTypeInternal _FrameResponse_default_instance_;
class PlayerState;
struct PlayerStateDefaultTypeInternal;
extern PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
}  // namespace game_ai
PROTOBUF_NAMESPACE_OPEN
template<> ::game_ai::FrameRequest* Arena::CreateMaybeMessage<::game_ai::FrameRequest>(Arena*);
template<> ::game_ai::FrameResponse* Arena::CreateMaybeMessage<::game_ai::FrameResponse>(Arena*);
template<> ::game_ai::PlayerState* Arena::CreateMaybeMessage<::game_ai::PlayerState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace game_ai {

// ===================================================================

class PlayerState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_ai.PlayerState) */ {
 public:
  inline PlayerState() : PlayerState(nullptr) {}
  ~PlayerState() override;
  explicit PROTOBUF_CONSTEXPR PlayerState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerState(const PlayerState& from);
  PlayerState(PlayerState&& from) noexcept
    : PlayerState() {
    *this = ::std::move(from);
  }

  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerState& operator=(PlayerState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerState& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerState* internal_default_instance() {
    return reinterpret_cast<const PlayerState*>(
               &_PlayerState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerState& a, PlayerState& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerState& from) {
    PlayerState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_ai.PlayerState";
  }
  protected:
  explicit PlayerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kWidthFieldNumber = 3,
    kHeightFieldNumber = 4,
    kHpPercentFieldNumber = 5,
    kDriveGaugeFieldNumber = 6,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float width = 3;
  void clear_width();
  float width() const;
  void set_width(float value);
  private:
  float _internal_width() const;
  void _internal_set_width(float value);
  public:

  // float height = 4;
  void clear_height();
  float height() const;
  void set_height(float value);
  private:
  float _internal_height() const;
  void _internal_set_height(float value);
  public:

  // int32 hp_percent = 5;
  void clear_hp_percent();
  int32_t hp_percent() const;
  void set_hp_percent(int32_t value);
  private:
  int32_t _internal_hp_percent() const;
  void _internal_set_hp_percent(int32_t value);
  public:

  // int32 drive_gauge = 6;
  void clear_drive_gauge();
  int32_t drive_gauge() const;
  void set_drive_gauge(int32_t value);
  private:
  int32_t _internal_drive_gauge() const;
  void _internal_set_drive_gauge(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_ai.PlayerState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float width_;
    float height_;
    int32_t hp_percent_;
    int32_t drive_gauge_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fai_2eproto;
};
// -------------------------------------------------------------------

class FrameRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_ai.FrameRequest) */ {
 public:
  inline FrameRequest() : FrameRequest(nullptr) {}
  ~FrameRequest() override;
  explicit PROTOBUF_CONSTEXPR FrameRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameRequest(const FrameRequest& from);
  FrameRequest(FrameRequest&& from) noexcept
    : FrameRequest() {
    *this = ::std::move(from);
  }

  inline FrameRequest& operator=(const FrameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameRequest& operator=(FrameRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameRequest* internal_default_instance() {
    return reinterpret_cast<const FrameRequest*>(
               &_FrameRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FrameRequest& a, FrameRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameRequest& from) {
    FrameRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_ai.FrameRequest";
  }
  protected:
  explicit FrameRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kImageDataFieldNumber = 3,
    kFrameIdFieldNumber = 1,
    kTimestampMsFieldNumber = 2,
  };
  // bytes image_data = 3;
  void clear_image_data();
  const std::string& image_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_image_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_image_data();
  PROTOBUF_NODISCARD std::string* release_image_data();
  void set_allocated_image_data(std::string* image_data);
  private:
  const std::string& _internal_image_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_data(const std::string& value);
  std::string* _internal_mutable_image_data();
  public:

  // uint64 frame_id = 1;
  void clear_frame_id();
  uint64_t frame_id() const;
  void set_frame_id(uint64_t value);
  private:
  uint64_t _internal_frame_id() const;
  void _internal_set_frame_id(uint64_t value);
  public:

  // uint64 timestamp_ms = 2;
  void clear_timestamp_ms();
  uint64_t timestamp_ms() const;
  void set_timestamp_ms(uint64_t value);
  private:
  uint64_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_ai.FrameRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_data_;
    uint64_t frame_id_;
    uint64_t timestamp_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fai_2eproto;
};
// -------------------------------------------------------------------

class FrameResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:game_ai.FrameResponse) */ {
 public:
  inline FrameResponse() : FrameResponse(nullptr) {}
  ~FrameResponse() override;
  explicit PROTOBUF_CONSTEXPR FrameResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameResponse(const FrameResponse& from);
  FrameResponse(FrameResponse&& from) noexcept
    : FrameResponse() {
    *this = ::std::move(from);
  }

  inline FrameResponse& operator=(const FrameResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameResponse& operator=(FrameResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameResponse* internal_default_instance() {
    return reinterpret_cast<const FrameResponse*>(
               &_FrameResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FrameResponse& a, FrameResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameResponse& from) {
    FrameResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "game_ai.FrameResponse";
  }
  protected:
  explicit FrameResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kP1StateFieldNumber = 2,
    kP2StateFieldNumber = 3,
    kFrameIdFieldNumber = 1,
    kInferenceLatencyMsFieldNumber = 4,
  };
  // .game_ai.PlayerState p1_state = 2;
  bool has_p1_state() const;
  private:
  bool _internal_has_p1_state() const;
  public:
  void clear_p1_state();
  const ::game_ai::PlayerState& p1_state() const;
  PROTOBUF_NODISCARD ::game_ai::PlayerState* release_p1_state();
  ::game_ai::PlayerState* mutable_p1_state();
  void set_allocated_p1_state(::game_ai::PlayerState* p1_state);
  private:
  const ::game_ai::PlayerState& _internal_p1_state() const;
  ::game_ai::PlayerState* _internal_mutable_p1_state();
  public:
  void unsafe_arena_set_allocated_p1_state(
      ::game_ai::PlayerState* p1_state);
  ::game_ai::PlayerState* unsafe_arena_release_p1_state();

  // .game_ai.PlayerState p2_state = 3;
  bool has_p2_state() const;
  private:
  bool _internal_has_p2_state() const;
  public:
  void clear_p2_state();
  const ::game_ai::PlayerState& p2_state() const;
  PROTOBUF_NODISCARD ::game_ai::PlayerState* release_p2_state();
  ::game_ai::PlayerState* mutable_p2_state();
  void set_allocated_p2_state(::game_ai::PlayerState* p2_state);
  private:
  const ::game_ai::PlayerState& _internal_p2_state() const;
  ::game_ai::PlayerState* _internal_mutable_p2_state();
  public:
  void unsafe_arena_set_allocated_p2_state(
      ::game_ai::PlayerState* p2_state);
  ::game_ai::PlayerState* unsafe_arena_release_p2_state();

  // uint64 frame_id = 1;
  void clear_frame_id();
  uint64_t frame_id() const;
  void set_frame_id(uint64_t value);
  private:
  uint64_t _internal_frame_id() const;
  void _internal_set_frame_id(uint64_t value);
  public:

  // int32 inference_latency_ms = 4;
  void clear_inference_latency_ms();
  int32_t inference_latency_ms() const;
  void set_inference_latency_ms(int32_t value);
  private:
  int32_t _internal_inference_latency_ms() const;
  void _internal_set_inference_latency_ms(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:game_ai.FrameResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::game_ai::PlayerState* p1_state_;
    ::game_ai::PlayerState* p2_state_;
    uint64_t frame_id_;
    int32_t inference_latency_ms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fai_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerState

// float x = 1;
inline void PlayerState::clear_x() {
  _impl_.x_ = 0;
}
inline float PlayerState::_internal_x() const {
  return _impl_.x_;
}
inline float PlayerState::x() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.x)
  return _internal_x();
}
inline void PlayerState::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void PlayerState::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.x)
}

// float y = 2;
inline void PlayerState::clear_y() {
  _impl_.y_ = 0;
}
inline float PlayerState::_internal_y() const {
  return _impl_.y_;
}
inline float PlayerState::y() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.y)
  return _internal_y();
}
inline void PlayerState::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void PlayerState::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.y)
}

// float width = 3;
inline void PlayerState::clear_width() {
  _impl_.width_ = 0;
}
inline float PlayerState::_internal_width() const {
  return _impl_.width_;
}
inline float PlayerState::width() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.width)
  return _internal_width();
}
inline void PlayerState::_internal_set_width(float value) {
  
  _impl_.width_ = value;
}
inline void PlayerState::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.width)
}

// float height = 4;
inline void PlayerState::clear_height() {
  _impl_.height_ = 0;
}
inline float PlayerState::_internal_height() const {
  return _impl_.height_;
}
inline float PlayerState::height() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.height)
  return _internal_height();
}
inline void PlayerState::_internal_set_height(float value) {
  
  _impl_.height_ = value;
}
inline void PlayerState::set_height(float value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.height)
}

// int32 hp_percent = 5;
inline void PlayerState::clear_hp_percent() {
  _impl_.hp_percent_ = 0;
}
inline int32_t PlayerState::_internal_hp_percent() const {
  return _impl_.hp_percent_;
}
inline int32_t PlayerState::hp_percent() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.hp_percent)
  return _internal_hp_percent();
}
inline void PlayerState::_internal_set_hp_percent(int32_t value) {
  
  _impl_.hp_percent_ = value;
}
inline void PlayerState::set_hp_percent(int32_t value) {
  _internal_set_hp_percent(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.hp_percent)
}

// int32 drive_gauge = 6;
inline void PlayerState::clear_drive_gauge() {
  _impl_.drive_gauge_ = 0;
}
inline int32_t PlayerState::_internal_drive_gauge() const {
  return _impl_.drive_gauge_;
}
inline int32_t PlayerState::drive_gauge() const {
  // @@protoc_insertion_point(field_get:game_ai.PlayerState.drive_gauge)
  return _internal_drive_gauge();
}
inline void PlayerState::_internal_set_drive_gauge(int32_t value) {
  
  _impl_.drive_gauge_ = value;
}
inline void PlayerState::set_drive_gauge(int32_t value) {
  _internal_set_drive_gauge(value);
  // @@protoc_insertion_point(field_set:game_ai.PlayerState.drive_gauge)
}

// -------------------------------------------------------------------

// FrameRequest

// uint64 frame_id = 1;
inline void FrameRequest::clear_frame_id() {
  _impl_.frame_id_ = uint64_t{0u};
}
inline uint64_t FrameRequest::_internal_frame_id() const {
  return _impl_.frame_id_;
}
inline uint64_t FrameRequest::frame_id() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameRequest.frame_id)
  return _internal_frame_id();
}
inline void FrameRequest::_internal_set_frame_id(uint64_t value) {
  
  _impl_.frame_id_ = value;
}
inline void FrameRequest::set_frame_id(uint64_t value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:game_ai.FrameRequest.frame_id)
}

// uint64 timestamp_ms = 2;
inline void FrameRequest::clear_timestamp_ms() {
  _impl_.timestamp_ms_ = uint64_t{0u};
}
inline uint64_t FrameRequest::_internal_timestamp_ms() const {
  return _impl_.timestamp_ms_;
}
inline uint64_t FrameRequest::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameRequest.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void FrameRequest::_internal_set_timestamp_ms(uint64_t value) {
  
  _impl_.timestamp_ms_ = value;
}
inline void FrameRequest::set_timestamp_ms(uint64_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:game_ai.FrameRequest.timestamp_ms)
}

// bytes image_data = 3;
inline void FrameRequest::clear_image_data() {
  _impl_.image_data_.ClearToEmpty();
}
inline const std::string& FrameRequest::image_data() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameRequest.image_data)
  return _internal_image_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FrameRequest::set_image_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.image_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:game_ai.FrameRequest.image_data)
}
inline std::string* FrameRequest::mutable_image_data() {
  std::string* _s = _internal_mutable_image_data();
  // @@protoc_insertion_point(field_mutable:game_ai.FrameRequest.image_data)
  return _s;
}
inline const std::string& FrameRequest::_internal_image_data() const {
  return _impl_.image_data_.Get();
}
inline void FrameRequest::_internal_set_image_data(const std::string& value) {
  
  _impl_.image_data_.Set(value, GetArenaForAllocation());
}
inline std::string* FrameRequest::_internal_mutable_image_data() {
  
  return _impl_.image_data_.Mutable(GetArenaForAllocation());
}
inline std::string* FrameRequest::release_image_data() {
  // @@protoc_insertion_point(field_release:game_ai.FrameRequest.image_data)
  return _impl_.image_data_.Release();
}
inline void FrameRequest::set_allocated_image_data(std::string* image_data) {
  if (image_data != nullptr) {
    
  } else {
    
  }
  _impl_.image_data_.SetAllocated(image_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.image_data_.IsDefault()) {
    _impl_.image_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:game_ai.FrameRequest.image_data)
}

// -------------------------------------------------------------------

// FrameResponse

// uint64 frame_id = 1;
inline void FrameResponse::clear_frame_id() {
  _impl_.frame_id_ = uint64_t{0u};
}
inline uint64_t FrameResponse::_internal_frame_id() const {
  return _impl_.frame_id_;
}
inline uint64_t FrameResponse::frame_id() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameResponse.frame_id)
  return _internal_frame_id();
}
inline void FrameResponse::_internal_set_frame_id(uint64_t value) {
  
  _impl_.frame_id_ = value;
}
inline void FrameResponse::set_frame_id(uint64_t value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:game_ai.FrameResponse.frame_id)
}

// .game_ai.PlayerState p1_state = 2;
inline bool FrameResponse::_internal_has_p1_state() const {
  return this != internal_default_instance() && _impl_.p1_state_ != nullptr;
}
inline bool FrameResponse::has_p1_state() const {
  return _internal_has_p1_state();
}
inline void FrameResponse::clear_p1_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.p1_state_ != nullptr) {
    delete _impl_.p1_state_;
  }
  _impl_.p1_state_ = nullptr;
}
inline const ::game_ai::PlayerState& FrameResponse::_internal_p1_state() const {
  const ::game_ai::PlayerState* p = _impl_.p1_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_ai::PlayerState&>(
      ::game_ai::_PlayerState_default_instance_);
}
inline const ::game_ai::PlayerState& FrameResponse::p1_state() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameResponse.p1_state)
  return _internal_p1_state();
}
inline void FrameResponse::unsafe_arena_set_allocated_p1_state(
    ::game_ai::PlayerState* p1_state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.p1_state_);
  }
  _impl_.p1_state_ = p1_state;
  if (p1_state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_ai.FrameResponse.p1_state)
}
inline ::game_ai::PlayerState* FrameResponse::release_p1_state() {
  
  ::game_ai::PlayerState* temp = _impl_.p1_state_;
  _impl_.p1_state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game_ai::PlayerState* FrameResponse::unsafe_arena_release_p1_state() {
  // @@protoc_insertion_point(field_release:game_ai.FrameResponse.p1_state)
  
  ::game_ai::PlayerState* temp = _impl_.p1_state_;
  _impl_.p1_state_ = nullptr;
  return temp;
}
inline ::game_ai::PlayerState* FrameResponse::_internal_mutable_p1_state() {
  
  if (_impl_.p1_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_ai::PlayerState>(GetArenaForAllocation());
    _impl_.p1_state_ = p;
  }
  return _impl_.p1_state_;
}
inline ::game_ai::PlayerState* FrameResponse::mutable_p1_state() {
  ::game_ai::PlayerState* _msg = _internal_mutable_p1_state();
  // @@protoc_insertion_point(field_mutable:game_ai.FrameResponse.p1_state)
  return _msg;
}
inline void FrameResponse::set_allocated_p1_state(::game_ai::PlayerState* p1_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.p1_state_;
  }
  if (p1_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(p1_state);
    if (message_arena != submessage_arena) {
      p1_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, p1_state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.p1_state_ = p1_state;
  // @@protoc_insertion_point(field_set_allocated:game_ai.FrameResponse.p1_state)
}

// .game_ai.PlayerState p2_state = 3;
inline bool FrameResponse::_internal_has_p2_state() const {
  return this != internal_default_instance() && _impl_.p2_state_ != nullptr;
}
inline bool FrameResponse::has_p2_state() const {
  return _internal_has_p2_state();
}
inline void FrameResponse::clear_p2_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.p2_state_ != nullptr) {
    delete _impl_.p2_state_;
  }
  _impl_.p2_state_ = nullptr;
}
inline const ::game_ai::PlayerState& FrameResponse::_internal_p2_state() const {
  const ::game_ai::PlayerState* p = _impl_.p2_state_;
  return p != nullptr ? *p : reinterpret_cast<const ::game_ai::PlayerState&>(
      ::game_ai::_PlayerState_default_instance_);
}
inline const ::game_ai::PlayerState& FrameResponse::p2_state() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameResponse.p2_state)
  return _internal_p2_state();
}
inline void FrameResponse::unsafe_arena_set_allocated_p2_state(
    ::game_ai::PlayerState* p2_state) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.p2_state_);
  }
  _impl_.p2_state_ = p2_state;
  if (p2_state) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:game_ai.FrameResponse.p2_state)
}
inline ::game_ai::PlayerState* FrameResponse::release_p2_state() {
  
  ::game_ai::PlayerState* temp = _impl_.p2_state_;
  _impl_.p2_state_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::game_ai::PlayerState* FrameResponse::unsafe_arena_release_p2_state() {
  // @@protoc_insertion_point(field_release:game_ai.FrameResponse.p2_state)
  
  ::game_ai::PlayerState* temp = _impl_.p2_state_;
  _impl_.p2_state_ = nullptr;
  return temp;
}
inline ::game_ai::PlayerState* FrameResponse::_internal_mutable_p2_state() {
  
  if (_impl_.p2_state_ == nullptr) {
    auto* p = CreateMaybeMessage<::game_ai::PlayerState>(GetArenaForAllocation());
    _impl_.p2_state_ = p;
  }
  return _impl_.p2_state_;
}
inline ::game_ai::PlayerState* FrameResponse::mutable_p2_state() {
  ::game_ai::PlayerState* _msg = _internal_mutable_p2_state();
  // @@protoc_insertion_point(field_mutable:game_ai.FrameResponse.p2_state)
  return _msg;
}
inline void FrameResponse::set_allocated_p2_state(::game_ai::PlayerState* p2_state) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.p2_state_;
  }
  if (p2_state) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(p2_state);
    if (message_arena != submessage_arena) {
      p2_state = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, p2_state, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.p2_state_ = p2_state;
  // @@protoc_insertion_point(field_set_allocated:game_ai.FrameResponse.p2_state)
}

// int32 inference_latency_ms = 4;
inline void FrameResponse::clear_inference_latency_ms() {
  _impl_.inference_latency_ms_ = 0;
}
inline int32_t FrameResponse::_internal_inference_latency_ms() const {
  return _impl_.inference_latency_ms_;
}
inline int32_t FrameResponse::inference_latency_ms() const {
  // @@protoc_insertion_point(field_get:game_ai.FrameResponse.inference_latency_ms)
  return _internal_inference_latency_ms();
}
inline void FrameResponse::_internal_set_inference_latency_ms(int32_t value) {
  
  _impl_.inference_latency_ms_ = value;
}
inline void FrameResponse::set_inference_latency_ms(int32_t value) {
  _internal_set_inference_latency_ms(value);
  // @@protoc_insertion_point(field_set:game_ai.FrameResponse.inference_latency_ms)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace game_ai

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_5fai_2eproto
